### ISSUE TITLE
__decay_t implementation (selection) fails with Clang 17

### ISSUE THREAD

**Issue by muellan** [NVIDIA/stdexec#1028] opened 2023-08-16 12:13 UTC
relevant code section: https://github.com/NVIDIA/stdexec/blob/48c52df0f81c6151eecf4f39fa5eed2dc0216204/include/stdexec/__detail/__type_traits.hpp#L29

**clang 17**
- preprocessor `__has_builtin(__decay)` fires, but then clang complains it doesn't have `__decay_t<_Ty>
- replacing it with std::decay_t works (of course)
- the "homegrown" implementation in the `#else` branch doesn't compile - clang complains it can't find `__declval` (which is *declared* at the start of the same file)

**Comment by muellan** [comment] 2023-08-16 13:50
just tried it - no, it doesn't help to namespace-qualify the call to `__declval`

I guess I just have to live with some customization for clang in this header for now.

**Comment by ericniebler** [comment] 2023-08-16 16:24
clang 17 doesn't officially exist yet. If you mean clang-trunk, then stdexec seems to work fine with it: https://godbolt.org/z/jMTWrKTqh

I also can't reproduce the error with just the `__decay_t` implementation:
https://godbolt.org/z/v5W1nKsK9

**Comment by muellan** [comment] 2023-08-16 17:25
Yes, I mean clang-trunk.
Just checked it again - it only seems to fail when compiling for the GPU (so when using clang as a CUDA compiler).

**Comment by miscco** [comment] 2023-08-16 18:07
My spider senses are tingling. You do not happen to have libstdc++ as standard library lying somewhere.

We had to completely shunt many builtins from recent clang, because they duplicate names from libstdc++

**Comment by ericniebler** [comment] 2024-01-12 17:13
This seems to be working, at least with stdexec trunk and the released version of clang-17. Closing.

**Closed by ericniebler** 2024-01-12 17:13 UTC
